// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4w94HPtKAlOxBwIGlecZ4cf1xPzkrGW4',
    appId: '1:105610266111:web:feb664e44a42e5903993ca',
    messagingSenderId: '105610266111',
    projectId: 'rhythmx-86624',
    authDomain: 'rhythmx-86624.firebaseapp.com',
    storageBucket: 'rhythmx-86624.firebasestorage.app',
    measurementId: 'G-YQ3NP5RQJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEe5ftC2aC83yFWS1AdUplAHmMXfnbrb0',
    appId: '1:105610266111:android:f72725a3c2d581d13993ca',
    messagingSenderId: '105610266111',
    projectId: 'rhythmx-86624',
    storageBucket: 'rhythmx-86624.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5f8R3QS1jjRp5sXx9HPHlbtUbfLxLJDQ',
    appId: '1:105610266111:ios:05162de60c7bb3b33993ca',
    messagingSenderId: '105610266111',
    projectId: 'rhythmx-86624',
    storageBucket: 'rhythmx-86624.firebasestorage.app',
    iosBundleId: 'com.example.rhythmixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5f8R3QS1jjRp5sXx9HPHlbtUbfLxLJDQ',
    appId: '1:105610266111:ios:05162de60c7bb3b33993ca',
    messagingSenderId: '105610266111',
    projectId: 'rhythmx-86624',
    storageBucket: 'rhythmx-86624.firebasestorage.app',
    iosBundleId: 'com.example.rhythmixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4w94HPtKAlOxBwIGlecZ4cf1xPzkrGW4',
    appId: '1:105610266111:web:666449bcb5efa0533993ca',
    messagingSenderId: '105610266111',
    projectId: 'rhythmx-86624',
    authDomain: 'rhythmx-86624.firebaseapp.com',
    storageBucket: 'rhythmx-86624.firebasestorage.app',
    measurementId: 'G-HHMJGSPPC8',
  );
}
